### ISSUE TITLE
not getting packed pos in loading

### ISSUE THREAD

**Issue by mei309** [litzvi/avc-beta#335]
im using this function 
 objectTableReader.findAvailableInventoryPoCodes(new ProductionUse[]{ProductionUse.ROAST, ProductionUse.PACKED});

**Comment by mei309** [comment]
its not giving if i use weightedPos in packing

**Comment by litzvi** [comment]
a dump would be helpful in this case

**Comment by mei309** [comment]
[Uploading Dump20210223.zip…]()

**Comment by mei309** [comment]
see po code 7777 and db id 45118

**Comment by mei309** [comment]
ABE-VND

**Comment by litzvi** [comment]
thanks

**Comment by litzvi** [comment]
pushed fix in Version: 11.3

**Comment by mei309** [comment]
antlr.NoViableAltException: unexpected AST node: {vector}
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2169) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2089) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.whereClause(HqlSqlBaseWalker.java:827) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:621) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:325) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:273) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:272) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:192) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:144) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:113) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:73) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]

**Comment by mei309** [comment]
edit mix works but getting inventory for a new one does not

**Comment by litzvi** [comment]
> getting inventory for a new one does not

don't understand

**Comment by mei309** [comment]
this error is always when i try getting mixed inventory

**Comment by litzvi** [comment]
I don't see it happening

**Comment by mei309** [comment]
i updated also front and also controllers. take them and try solving it

**Comment by litzvi** [comment]
I don't see the problem.
Also you should show poCodes in Material to load (now you are showing poCode)

**Comment by litzvi** [comment]
> i updated also front and also controllers. take them and try solving it

I don't know what to solve. maybe we are not synchronized.
I'll push again and check if it's still a problem

**Comment by litzvi** [comment]
pushed 11.4

**Comment by mei309** [comment]
it still happens

**Comment by mei309** [comment]
call me

**Comment by litzvi** [comment]
sorry. didn't have my phone.
now i have

**Comment by litzvi** [comment]
fixed. from Version: 11.5

**Comment by litzvi** [comment]
By the way, you should show the poCodes of the available inventory items when choosing.
Also use poCodes in display of usedItems (details)

**Comment by mei309** [comment]
can you do a function for sql to change all groupName === 'normalLoding' to groupName === 'normalPos'?

**Comment by mei309** [comment]
its done. but please send me that function

**Comment by litzvi** [comment]
Update ebdb.process_groups set group_name='normalPos' where group_name='normalLoding' and id>-1;

**Comment by mei309** [comment]
ok done
