### ISSUE TITLE
Change shipping, inventoryUse as relocation

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#540]
- regard shipped as inventory in a different location (production functionality)
- exclude relevant production functionalities from inventory.
- easy to calculate loss in production and shipped inventory.

**Comment by litzvi** [comment]
enforce loading production functionality

**Comment by litzvi** [comment]
later when we see everything works fine we need to consider inventory use - not now.

**Comment by mei309** [comment]
> I changed the used items in loading to storage moves.
> Need to run this file on cloud date (will only work if you import data only). 
> 
> [VERSION_8_CHANGES.zip](https://github.com/litzvi/avc-beta/files/6807881/VERSION_8_CHANGES.zip)
> 
> ask me for a ready backup if you need.
> 
> 

share with me

**Comment by litzvi** [comment]
[Dump20210714 (1).zip](https://github.com/litzvi/avc-beta/files/6812685/Dump20210714.1.zip)

**Comment by litzvi** [comment]
By the way, when changing shipping from used to moves, don't forget to add the item po code for every line in the loading details (in relocation you don't show it)

**Comment by mei309** [comment]
done

**Comment by litzvi** [comment]
This is about the class com.avc.mis.beta.entities.process.InventoryUse (nothing to do with using ingridients in production).

I changed it, so it's a relocation (same as loading) and has storageMoveGroups instead of usedItemGroups.
don't forget

- set suitable production functionality GENERAL_USE, PRODUCT_USE for GeneralInventoryUse and ProductInventoryUse respectively. 
- look at the messages in this issue we had with loading as they are the same.

**Comment by litzvi** [comment]
If you are running it on an existing database, then you can run this.
[VERSION_9_CHANGES.zip](https://github.com/litzvi/avc-beta/files/6873638/VERSION_9_CHANGES.zip)

**Comment by mei309** [comment]
2021-07-29 00:50:54.027 ERROR 12060 --- [nio-8080-exec-7] o.h.engine.jdbc.spi.SqlExceptionHelper   : Cannot add or update a child row: a foreign key constraint fails (`ebdb`.`inventory_uses`, CONSTRAINT `FKape7yn6jnuhjq7m9mwkvqmn73` FOREIGN KEY (`process_id`) REFERENCES `transaction_processes` (`process_id`))
2021-07-29 00:50:54.036 ERROR 12060 --- [nio-8080-exec-7] com.avc.mis.beta.ExceptionControler      : Exception : 

java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`ebdb`.`inventory_uses`, CONSTRAINT `FKape7yn6jnuhjq7m9mwkvqmn73` FOREIGN KEY (`process_id`) REFERENCES `transaction_processes` (`process_id`))
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) ~[mysql-connector-java-8.0.20.jar:8.0.20]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar:na]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
	at org.hibernate.pe

**Comment by mei309** [comment]
you know whats this?

**Comment by litzvi** [comment]
Yes it's because you are using old database where inventory use is a transaction process.

**Comment by litzvi** [comment]
> If you are running it on an existing database, then you can run this.
> [VERSION_9_CHANGES.zip](https://github.com/litzvi/avc-beta/files/6873638/VERSION_9_CHANGES.zip)

if you are running the cloud backup, you need to run this first.

**Comment by mei309** [comment]
I ran it

**Comment by mei309** [comment]
I will try again tonight

**Comment by litzvi** [comment]
> I ran it

you need to run it on the old db with the old data. You can't mix a new db with old data

**Comment by mei309** [comment]
im doing exactly that and its not working

**Comment by litzvi** [comment]
It's working by me. So you need to write exactly when it's happening.

**Comment by litzvi** [comment]
[Cloud_20210802.zip](https://github.com/litzvi/avc-beta/files/6915667/Cloud_20210802.zip)

**Comment by mei309** [comment]
for some reason numberAvailableUnits is always null. in StorageMovesGroupDTO

**Comment by litzvi** [comment]
I see it's showing. You aren't showing it in edit but it is there (in F12).

**Comment by mei309** [comment]
ok done
